services:
  web:
    build: 
      context: ..
      dockerfile: docker/Dockerfile
    container_name: social_network_app
    env_file:
      # GET all the variables from the .env file
      - ../.env
    volumes:
      - ../app:/app
    ports:
      - "8000:8000"

